[no-exit-message]
test-drive:
  ZDOTDIR={{ quote(justfile_directory()) }} zsh --no-globalrcs -i
  @echo '-- test-drive finished --'

benchmark-startup:
  time ZDOTDIR={{ quote(justfile_directory()) }} zsh --no-globalrcs -i -c exit

update-dircolors:
  #!/usr/bin/env bash
  (
    echo '# This file is automatically generated, do not edit.'
    echo '__zk_dircolors() {'
    echo 'typeset -g LS_COLORS'
    TERM=xterm dircolors -b {{ quote(justfile_directory()) }}/dircolors.conf
    echo '}'
  ) > {{ quote(justfile_directory()) }}/aliases/__zk_dircolors
